---
title: "dwv"
output: html_document
---
```{r}
library(zoo)
library(lmtest)
```

```{r}
test_dwtest <- function(n,k,rho,iterations, maxfile = 100, platform = c("Unix","Windows")){
  pvals_r <- rep()
  pvals_t <- rep()
  pvals_l <- rep()
  nd = 0
  s = '/'
  if (iterations%%maxfile != 0){
    nd <- as.integer(iterations/maxfile) + 1
  }
  else{
    nd <- as.integer(iterations/maxfile)
  }
  ns  <- paste(as.character(n),as.character(k),as.character(rho),sep = "_") # n_k_rho
  # ---------- platform dependent ---------- #
  if (platform == 'u')   # for unix-like
      s = '/'
  else if (platform == 'w') # for windows
      s = '\\'
  # ------------ cd to test_ds ------------- #
  setwd("test_ds")
  setwd(ns)
  # ----------- compute formula ------------ #
  tmp = c()
  for( i in c(1:k))
    tmp[[i]]<- paste("x",as.character(i),sep ="")
  formulas <-paste("y ~ ",paste(tmp,collapse = " + "),sep="")
  # ---------------------------------------- #
  for(i in c(0:(nd-1))){
    setwd( paste(ns,as.character(i+1),sep = "_") )
    #print(getwd())
    if(i ==nd-1 && iterations%%maxfile != 0)
      for(j in c(0:(iterations%%maxfile-1))){
        df <- read.csv(paste( paste(ns,as.character(i+1),sep = "_"), paste("_",as.character(j+1+maxfile*i),sep = ""), ".csv",sep = ""))
        pvals_r[j+1+maxfile*i] <- dwtest(as.formula(formulas),data=df,alternative = "greater")[4]
        pvals_t[j+1+maxfile*i] <- dwtest(as.formula(formulas),data=df,alternative = "two.sided")[4]
        pvals_l[j+1+maxfile*i] <- dwtest(as.formula(formulas),data=df,alternative = "less")[4]
      }
    else
      for(j in c(0:(maxfile-1))){
        df <- read.csv(paste( paste(ns,as.character(i+1),sep = "_"), paste("_",as.character(j+1+maxfile*i),sep = ""), ".csv",sep = ""))
        pvals_r[j+1+maxfile*i] <- dwtest(as.formula(formulas),data=df,alternative = "greater")[4]
        pvals_t[j+1+maxfile*i] <- dwtest(as.formula(formulas),data=df,alternative = "two.sided")[4]
        pvals_l[j+1+maxfile*i] <- dwtest(as.formula(formulas),data=df,alternative = "less")[4]
      }
    setwd( paste("..",s,sep = "") )
  }
  setwd( paste("..",s,sep = "") )
  setwd( paste("..",s,sep = "") )
  # -------------------
  setwd("rresult_ds1")
  dftmp <- do.call(rbind,Map(data.frame, right = pvals_r, twotail = pvals_t, left = pvals_l))
  #write.csv(dftmp,paste(paste("r","pval",ns,sep = "_"),".csv",sep =""), row.names = FALSE)
  write.csv(dftmp,paste(paste("r",paste("pval",ns,sep = ""),sep = "_"),".csv",sep =""), row.names = FALSE)
  setwd(paste("..",s,sep = ""))
  # ------------------
}
```


```{r}
nlist <- c(10,20,50,100,200,500,1000)
klist <- c(1,2,3,5,10)
rholist <- c(0,0.1,0.3,0.5)
it <- 5000

```

```{r}
pnlist <- c(10,20,50,100,200,500,1000)
for(i in pnlist){
  for(j in klist){
    if(i == j)
      next
    for(k in rholist){
      test_dwtest(i,j,k,it)
    }
  }
}
```

```{r}
for(j in klist){
  if(j == 10)
    next
  for(k in rholist){
    test_dwtest(10,j,k,it)
  }
}
```

```{r}
for(j in klist){
  for(k in rholist){
    test_dwtest(20,j,k,it)
  }
}
```

```{r}
for(j in klist){
  for(k in rholist){
    test_dwtest(50,j,k,it)
  }
}
```

```{r}
for(j in klist){
  for(k in rholist){
    test_dwtest(100,j,k,it)
  }
}
```

```{r}
for(j in klist){
  for(k in rholist){
    test_dwtest(200,j,k,it)
  }
}
```

```{r}
for(j in klist){
  for(k in rholist){
    test_dwtest(500,j,k,it)
  }
}
```

```{r}
for(j in klist){
  for(k in rholist){
    test_dwtest(1000,j,k,it)
  }
}
```



```{r}
dftest <- read.csv("test_ds/10_1_0/10_1_0_1/10_1_0_1_8.csv")
print(dwtest(y ~ x1,data=dftest,alternative = "greater")[4])

```
